Backstage/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index_Desktop, name='Desktop'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^welcome/(?P<page>\d+)$', views.welcome, name='welcome'),
    url(r'^users/$', views.users, name='users'),
    url(r'^student/$', views.students_Add, name='students'),
    url(r'^student/(?P<page>\d+)/$', views.students_Add, name='students'),

    url(r'^add_student/$',views.add_user,name='add_shudent'),
    url(r'^add_student/(?P<page>\d+)/$',views.add_user,name='add_shudent'),
    url(r'views/(?P<id>\d+)/',views.views_user,name='viewx'),
    url(r'^student_del/$', views.students_Del, name='students_del'),
    url(r'^student_del/(?P<page>\d+)$', views.students_Del, name='students_del'),
    url(r'^category/$', views.category, name='category'),
    # url(r'^category_add/$',views.category_add,name='category_add'),
    # url(r'^category_small/$',views.category_small,name='category_small'),
    url(r'^login/$', views.login, name='login'),
    url(r'^registered/$', views.registered, name='registered'),

    url(r'^commodity/(?P<page>\d+)/$', views.commodity_list, name='commodity'),
    url(r'^commodity/$', views.commodity_list, name='commodity'),
    url(r'^add_commodity/$', views.add_commodity, name='add_commodity'),
    url(r'^del_commodity/$', views.del_commodity, name='del_commodity'),
    url(r'^del_commodity/(?P<page>\d+)/$', views.del_commodity, name='del_commodity'),
    # 批量删除
    url(r'^batch_deletions/$', views.batchdeletion, name='batch_deletion'),
    url(r'^batch_deletions/(?P<page>\d+)/$', views.batchdeletion, name='batch_deletion'),
    url(r'^batch_restore/$', views.batchrestore, name='batch_restore'),
    url(r'^batch_restore/(?P<page>\d+)/$', views.batchrestore, name='batch_restore'),

]

Backstage/Backstage/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("App.urls", namespace='app'))
]

Backstage/templates/classUpdate.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="Css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="Css/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="Css/style.css" />
    <script type="text/javascript" src="Js/jquery2.js"></script>
    <script type="text/javascript" src="Js/jquery2.sorted.js"></script>
    <script type="text/javascript" src="Js/bootstrap.js"></script>
    <script type="text/javascript" src="Js/ckform.js"></script>
    <script type="text/javascript" src="Js/common.js"></script>
    <script type="text/javascript" src="Js/jquerypicture.js"></script>
    
    <style type="text/css">
        body {font-size: 20px;
            padding-bottom: 40px;
            background-color:#e9e7ef;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
</head>
<body>
<font color="#777777"><strong>修改大类：</strong></font> 
<form action="#" method="post" class="definewidth m20" enctype="multipart/form-data">
<table style="margin-left:10px;margin-top:3px;">
    <tr>
         <td>大类名称：</td>
		 <td><input type="text" name="classname"/></td>
    </tr>
	<tr>
         <td>介绍：</td>
		 <td><input type="text" name="classname" style="height: 100px;wight：200px;"/></td>
    </tr>
	
    <tr>
        
       <td>
            <button style="margin-left:5px;"type="submit" class="btn btn-primary" type="button"  >保&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp存</button> &nbsp;&nbsp;<button type="button" class="btn btn-success" name="backid" id="backid"> <a href="classQuery.html"> 返回列表</a></button>
        </td>
    </tr>
</table>
</form>


</body>
</html>


Backstage/templates/commodity_del.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body class="layui-anim layui-anim-up">
<div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"
       href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
</div>
<div class="x-body">

    <xblock>

        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量恢复</button>
        <span class="x-right" style="line-height:40px">共有数据：{{ isdels|length }} 条</span>
    </xblock>
    <table class="layui-table">
        <thead>
        <tr>
            <th>
                <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i
                        class="layui-icon">&#xe605;</i></div>
            </th>
            <th>商品名称</th>
            <th>商品编号</th>
            <th>表盘</th>
            <th>标签</th>
            <th>表壳</th>
            <th>宝石镶嵌</th>
            <th>表带</th>
            <th>类别</th>
            <th>描述</th>


        </tr>
        </thead>
        <tbody>
        {% for use in pagetion %}

        {% if use.is_delete == 1 %}

            <tr>
                <td>
                    <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='{{ use.id }}'><i
                            class="layui-icon">&#xe605;</i></div>
                </td>
                <td style="width: 100px">{{ use.cname }}</td>
                <td style="width: 100px">{{ use.sku }}</td>
                <td>{{ use.plate }}</td>

                {% if use.tag == '1' %}
                    <td style="width: 50px">男式</td>
                {% else %}
                    <td style="width: 50px">女式</td>
                {% endif %}
                <td>{{ use.case }}</td>

                <td style="width: 75px">{{ use.gem }}</td>
                <td>{{ use.strap }}</td>
                <td style="width: 100px">{{ use.sid.s_name }}</td>
                <td>
                    {{ use.description }}
                </td>

            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <div class="page">
        <div>
            <ul>

                <li style="display: inline"><a class="prev" href="{% url 'app:batch_restore' page=1 %}">&lt;&lt;</a></li>
                {% for page in pagetor.page_range %}
                    {% if page == pagetion.number %}
                        <li style="display: inline" class="item active">
                            <a class="num" name="page" href="{% url 'app:batch_restore' page %}">{{ page }}</a></li>
                    {% else %}
                        <li style="display: inline">
                            <a class="num" name="page" href="{% url 'app:batch_restore' page %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}

                <li style="display: inline"><a class="next" href="{% url 'app:batch_restore' page=pagetor.num_pages %}">&gt;&gt;</a>
                </li>

            </ul>
        </div>
    </div>

</div>
<script>
    layui.use('laydate', function () {
        var laydate = layui.laydate;

        //执行一个laydate实例
        laydate.render({
            elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
            elem: '#end' //指定元素
        });
    });

    /*用户-停用*/
    function member_stop(obj, id) {
        layer.confirm('确认要停用吗？', function (index) {

            if ($(obj).attr('title') == '启用') {

                //发异步把用户状态进行更改
                $(obj).attr('title', '停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!', {icon: 5, time: 1000});

            } else {
                $(obj).attr('title', '启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!', {icon: 5, time: 1000});
            }

        });
    }

    /*用户-删除*/
    function member_del(obj, id) {
        layer.confirm('确认要恢复吗？', function (index) {
            //发异步删除数据
            $(obj).parents("tr").remove();
            layer.msg('已恢复!', {icon: 1, time: 1000});
        });
    }


    function delAll(argument) {

        var data = tableCheck.getData();

        layer.confirm('确认要恢复吗？' + data, function (index) {
            //捉到所有被选中的，发异步进行删除
            window.location='http://127.0.0.1:8000/batch_restore/?page=1&data='+data;
            layer.msg('恢复成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
    }
</script>

</body>

</html>

Backstage/templates/commodity_list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->




</head>

<body class="layui-anim layui-anim-up">
<div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"
       href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
</div>
<div class="x-body">

    <xblock>

        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" name="adds" value="3"
                onclick="x_admin_show('添加用户','{% url 'app:add_commodity' %}',600,400)"><i class="layui-icon"></i>添加
        </button>

        <span class="x-right" style="line-height:40px">共有数据：{{ isdel|length }} 条</span>

    </xblock>

        <table class="layui-table">
            <thead>
            <tr>
                <th>
                   <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i
                        class="layui-icon">&#xe605;</i></div>

                </th>
                <th>商品名称</th>
                <th>商品编号</th>
                <th>表盘</th>
                <th>标签</th>
                <th>表壳</th>
                <th>宝石镶嵌</th>
                <th>表带</th>
                <th>类别</th>
                <th>描述</th>


            </tr>
            </thead>
            <tbody>
            {% for use in pagetion %}

                {% if use.is_delete == 0 %}

                    <tr>
                        <td>
                    <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='{{ use.id }}'><i
                            class="layui-icon">&#xe605;</i></div>
                        </td>
                        <td style="width: 100px">{{ use.cname }}</td>
                        <td style="width: 100px">{{ use.sku }}</td>
                        <td>{{ use.plate }}</td>

                        {% if use.tag == '1' %}
                            <td style="width: 50px">男式</td>
                        {% else %}
                            <td style="width: 50px">女式</td>
                        {% endif %}
                        <td>{{ use.case }}</td>

                        <td style="width: 75px">{{ use.gem }}</td>
                        <td>{{ use.strap }}</td>
                        <td style="width: 100px">{{ use.sid.s_name }}</td>
                        <td>
                            {{ use.description }}
                        </td>

                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>

        </table>


    <div class="page">
        <div>
            <ul>

                <li style="display: inline"><a class="prev" href="{% url 'app:batch_deletion' page=1 %}">&lt;&lt;</a>
                </li>
                {% for page in pagetor.page_range %}
                    {% if page == pagetion.number %}
                        <li style="display: inline" class="item active">
                            <a class="num" name="page" href="{% url 'app:batch_deletion' page=page %}">{{ page }}</a></li>
                    {% else %}
                        <li style="display: inline">
                            <a class="num" name="page" href="{% url 'app:batch_deletion' page=page %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}

                <li style="display: inline"><a class="next" href="{% url 'app:batch_deletion' page=pagetor.num_pages %}">&gt;&gt;</a>
                </li>

            </ul>
        </div>
    </div>

</div>
<script>
    layui.use('laydate', function () {
        var laydate = layui.laydate;

        //执行一个laydate实例
        laydate.render({
            elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
            elem: '#end' //指定元素
        });
    });

    /*用户-停用*/
    function member_stop(obj, id) {
        layer.confirm('确认要停用吗？', function (index) {

            if ($(obj).attr('title') == '启用') {

                //发异步把用户状态进行更改
                $(obj).attr('title', '停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!', {icon: 5, time: 1000});

            } else {
                $(obj).attr('title', '启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!', {icon: 5, time: 1000});
            }

        });
    }

    /*用户-删除*/
    function member_del(obj, id) {
        layer.confirm('确认要删除吗？', function (index) {
            //发异步删除数据
            $(obj).parents("tr").remove();
            layer.msg('已删除!', {icon: 1, time: 1000});
        });
    }


    function delAll(argument) {


        var data = tableCheck.getData();

        layer.confirm('确认要删除吗？' + data, function (index) {
            //捉到所有被选中的，发异步进行删除
            {#window.location='http://127.0.0.1:8000/batch_deletions/?data='+data;#}
            window.location='http://127.0.0.1:8000/batch_deletions/?page=1&data='+data;
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
    }
</script>

</body>

</html>

Backstage/templates/member-list.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport"
          content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body class="layui-anim layui-anim-up">
<div class="x-nav">
      <span class="layui-breadcrumb">
        <a href="">首页</a>
        <a href="">演示</a>
        <a>
          <cite>导航元素</cite></a>
      </span>
    <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"
       href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
</div>
<div class="x-body">
    <div class="layui-row">
        <form class="layui-form layui-col-md12 x-so">
            <input class="layui-input" placeholder="开始日" name="start" id="start">
            <input class="layui-input" placeholder="截止日" name="end" id="end">
            <input type="text" name="username" placeholder="请输入用户名" autocomplete="off" class="layui-input">
            <button class="layui-btn" lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
        </form>
    </div>
    <xblock>

        <button class="layui-btn layui-btn-danger" onclick="delAll()"><i class="layui-icon"></i>批量删除</button>
        <button class="layui-btn" name="adds" value="3"
                onclick="x_admin_show('添加用户','{% url 'app:registered' %}',600,400)"><i class="layui-icon"></i>添加
        </button>
        <span class="x-right" style="line-height:40px">共有数据：{{ isactive|length }} 条</span>
    </xblock>
    <table class="layui-table">
        <thead>
        <tr>
            <th>
                <div class="layui-unselect header layui-form-checkbox" lay-skin="primary"><i
                        class="layui-icon">&#xe605;</i></div>
            </th>
            <th>ID</th>
            <th>名</th>
            <th>姓</th>
            <th>性别</th>
            <th>手机</th>
            <th>邮箱</th>
            <th>地址</th>
            <th>加入时间</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for use in pagetion %}
            {% if use.is_active == 1 %}


                <tr>
                    <td>
                        <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='{{ use.uid }}'><i
                                class="layui-icon">&#xe605;</i></div>
                    </td>
                    <td>{{ use.uid }}</td>
                    <td>{{ use.first_name }}</td>
                    <td>{{ use.last_name }}</td>

                    {% if use.gender == 1 %}
                        <td>男</td>
                    {% else %}
                        <td>女</td>
                    {% endif %}
                    <td>{{ use.mobile }}</td>
                    <td>{{ use.email }}</td>
                    <td>{{ use.address }}</td>
                    <td>
                        {{ use.date_joined }}
                    </td>
                    <td class="td-status">
                        <span class="layui-btn layui-btn-normal layui-btn-mini">已启用</span></td>
                    <td class="td-manage">
                        <a onclick="member_stop(this,'10001')" href="javascript:;" title="启用">
                            <i class="layui-icon">&#xe601;</i>
                        </a>
                        <a title="编辑" onclick="x_admin_show('编辑','member-edit.html',600,400)" href="javascript:;">
                            <i class="layui-icon">&#xe642;</i>
                        </a>
                        <a onclick="x_admin_show('修改密码','member-password.html',600,400)" title="修改密码"
                           href="javascript:;">
                            <i class="layui-icon">&#xe631;</i>
                        </a>
                        <a title="删除" onclick="member_del(this,'要删除的id')" href="javascript:;">
                            <i class="layui-icon">&#xe640;</i>
                        </a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <div class="page">
        <div>
            <ul>

                <li style="display: inline"><a class="prev" href="{% url 'app:add_shudent' page=1 %}">&lt;&lt;</a></li>
                {% for page in pagetor.page_range %}
                    {% if page == pagetion.number %}
                        <li style="display: inline" class="item active">
                            <a class="num" name="page" href="{% url 'app:add_shudent' page=page %}">{{ page }}</a></li>
                    {% else %}
                        <li style="display: inline">
                            <a class="num" name="page" href="{% url 'app:add_shudent' page=page %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}

                <li style="display: inline"><a class="next" href="{% url 'app:add_shudent' page=pagetor.num_pages %}">&gt;&gt;</a>
                </li>

            </ul>
        </div>
    </div>

</div>
<script>
    layui.use('laydate', function () {
        var laydate = layui.laydate;

        //执行一个laydate实例
        laydate.render({
            elem: '#start' //指定元素
        });

        //执行一个laydate实例
        laydate.render({
            elem: '#end' //指定元素
        });
    });

    /*用户-停用*/
    function member_stop(obj, id) {
        layer.confirm('确认要停用吗？', function (index) {

            if ($(obj).attr('title') == '启用') {

                //发异步把用户状态进行更改
                $(obj).attr('title', '停用')
                $(obj).find('i').html('&#xe62f;');

                $(obj).parents("tr").find(".td-status").find('span').addClass('layui-btn-disabled').html('已停用');
                layer.msg('已停用!', {icon: 5, time: 1000});

            } else {
                $(obj).attr('title', '启用')
                $(obj).find('i').html('&#xe601;');

                $(obj).parents("tr").find(".td-status").find('span').removeClass('layui-btn-disabled').html('已启用');
                layer.msg('已启用!', {icon: 5, time: 1000});
            }

        });
    }

    /*用户-删除*/
    function member_del(obj, id) {
        layer.confirm('确认要删除吗？', function (index) {
            //发异步删除数据
            $(obj).parents("tr").remove();
            layer.msg('已删除!', {icon: 1, time: 1000});
        });
    }


    function delAll(argument) {

        var data = tableCheck.getData();

        layer.confirm('确认要删除吗？' + data, function (index) {
            //捉到所有被选中的，发异步进行删除
            window.location = 'http://127.0.0.1:8001/add_student/?page=1&data=' + data;
            layer.msg('删除成功', {icon: 1});
            $(".layui-form-checked").not('.header').parents('tr').remove();
        });
    }
</script>

</body>

</html>

Backstage/templates/studentQuery.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
    <script type="text/javascript" src="/static/js/jquery2.js"></script>
    <script type="text/javascript" src="/static/js/jquery2.sorted.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/ckform.js"></script>
    <script type="text/javascript" src="/static/js/common.js"></script>

    <style type="text/css">
        body {font-size: 20px;
            padding-bottom: 40px;
            background-color:#e9e7ef;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
</head>
<body>
<form class="form-inline definewidth m20" action="#" method="get">
     <font color="#777777"><strong>用户姓名:</strong></font>
    <input type="text" name="menuname" id="menuname"class="abc input-default" placeholder="" value="">&nbsp;&nbsp; 
    <button type="submit" class="btn btn-primary">查询</button> 
</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>

    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        
       
        <th>创建时间</th>
		 <th>冻结账户</th>

     </tr>
    </thead>
    {% for user in uses %}
        <tr>
                <td><a href="{% url 'app:users' %}">{{ user.first_name}}</a></td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                
                <td>{{ user.date_joined }}</td>
				<td><button type="submit">注销</button></td>
          
        </tr>
           
       {% endfor %}
       </table>

</body>
</html>

Backstage/templates/videoQuery.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/style.css" />
    <script type="text/javascript" src="/static/js/jquery2.js"></script>
    <script type="text/javascript" src="/static/js/jquery2.sorted.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/ckform.js"></script>
    <script type="text/javascript" src="/static/js/common.js"></script>

    <style type="text/css">
        body {font-size: 20px;
		font-size: 20px;
            padding-bottom: 40px;
            background-color:#e9e7ef;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
</head>
<body >
<form class="form-inline definewidth m20" action="#" method="get">
    <font color="#777777"><strong>订单名称:</strong></font>
    <input type="text" name="menuname" id="menuname"class="abc input-default" placeholder="" value="">&nbsp;&nbsp; 
    <button type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp; 

</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>
    <tr>
        <th>订单名称</th>
        
        <th>分类</th>
        <th>上传者</th>
        <th>上传日期</th>
        
        
        <th>管理菜单</th>
    </tr>
    </thead>
	     
        <tr>
                <td>复仇者联盟</td>
                <td>电影</td>
                <td><a href="{% url 'app:users' %}">小强</a></td>
                <td>2016.07.22</td>
                
                <td> <button type="submit">删除</button></td>
               
        </tr>
           
       
       </table>

</body>
</html>