Reception/App/urls.py
from django.conf.urls import url

from App import views, mine

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^product/(?P<sid>\d+)/$', views.product, name='product'),
    url(r'^product/(?P<sid>\d+)/(?P<tag>\d+)/$', views.product, name='product'),

    url(r'^account/$', views.account, name='account'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),

    url(r'^single/(?P<cid>\d+)/$', views.single, name='single'),

    url(r'^cart/$', views.cart, name='cart'),
    url(r'^additem/(?P<cid>\d+)/$', views.add_to_cart, name='additem'),
    url(r'^removeitem/(?P<cid>\d+)/$', views.remove_from_cart, name='removeitem'),
    url(r'^emptyitems/$', views.empty_from_cart, name='emptyitems'),

    url(r'^sellteaccounts/$', views.sellteaccounts, name='sellteaccounts'),
    url(r'^pay/$', views.pay, name='pay'),
    url(r'^finish/$', views.finish, name='finish'),
    url(r'^repay/$', views.repay, name='repay'),

    url(r'^orders/$', views.orders, name='orders'),
    url(r'^deleteorder/$', views.deleteorder, name='deleteorder'),

    url(r'^contact/$', views.contact, name='contact'),

    url(r'^confirm/$', views.confirm, name='confirm'),

    url(r'^password/$', views.newpassword, name='password'),
    url(r'^info/$', views.info, name='info'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^reset_password/$',views.reset_password,name='reset_password'),

    url(r'^search/$', views.search, name='search'),

    url(r'^user/(?P<pk>\d+)/$', mine.UserAPIView.as_view(), name='user'),

]

Reception/Reception/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('App.urls', namespace='app')),

]

Reception/templates/account.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Account{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Account</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--account-starts-->
    <div class="account">
        <div class="container">
            <div class="account-top heading">
                <h2>ACCOUNT</h2>
            </div>
            <div class="account-main">
                <div class="col-md-6 account-left">
                    <h3>Existing User</h3>
                    <div class="account-bottom">
                        <form method="post" action="{% url 'app:account' %}">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ next }}">
                            <input placeholder="Email" name="email" type="text" tabindex="3" required>
                            <input placeholder="Password" name="password" type="password" tabindex="4" required>
                            <div class="address">
                                <a class="forgot" href="{% url 'app:reset' %}">Forgot Your Password?</a>
                                <input type="submit" value="Login">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6 account-right account-left">
                    <h3>New User? Create an Account</h3>
                    <p>By creating an account with our store, you will be able to move through the checkout process
                        faster,
                        store multiple shipping addresses, view and track your orders in your account and more.</p>
                    <a href="{% url 'app:register' %}">Create an Account</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--account-end-->
{% endblock %}

Reception/templates/checkout.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Checkout{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Checkout</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--start-ckeckout-->
    <div class="ckeckout">
        <div class="container">
            <div class="ckeck-top heading">
                <h2>CHECKOUT</h2>
            </div>
            <div class="ckeckout-top">
                <div class="cart-items">
                    <h3>My Shopping Bag ({{ cartList.count }})</h3>
                    <script>$(document).ready(function (c) {
                        $('.close1').on('click', function (c) {
                            $('.cart-header').fadeOut('slow', function (c) {
                                $('.cart-header').remove();
                            });
                        });
                    });
                    </script>
                    <script>$(document).ready(function (c) {
                        $('.close2').on('click', function (c) {
                            $('.cart-header1').fadeOut('slow', function (c) {
                                $('.cart-header1').remove();
                            });
                        });
                    });
                    </script>
                    <script>$(document).ready(function (c) {
                        $('.close3').on('click', function (c) {
                            $('.cart-header2').fadeOut('slow', function (c) {
                                $('.cart-header2').remove();
                            });
                        });
                    });
                    </script>

                    <div class="in-check">
                        <ul class="unit">
                            <li><span>Item</span></li>
                            <li><span>Product Name</span></li>
                            <li><span>Unit Price / Amount</span></li>
                            <li><span>Subtotal / Delivery Details</span></li>
                            <li></li>
                            <div class="clearfix"></div>
                        </ul>
                        {% for commodity in cartList %}
                            <ul class="cart-header">
                                <a href="{% url 'app:removeitem' cid=commodity.product.id %}">
                                    <div class="close1"></div>
                                </a>
                                <li class="ring-in">
                                    <a href="{% url 'app:single' cid=commodity.product.id %}">
                                        <img src="/static/upload/{{ commodity.product.picture_1 }}"
                                             class="img-responsive"
                                             alt="{{ commodity.product.cname }}" style="width: 100px;">
                                    </a>
                                </li>
                                <li><span class="name">{{ commodity.product.sku }}</span></li>
                                <li>
                                    <span class="cost">
                                    $ {{ commodity.product.price }} / {{ commodity.quantity }}
                                    </span>
                                </li>
                                <li><span>$ {{ commodity.total_price }} / Free</span>
                                    <p>Delivered in 2-3 business days</p></li>
                                <div class="clearfix"></div>
                            </ul>
                        {% endfor %}
                        {% if cartList.count > 0 %}
                            <ul class="cart-header">

                                <div></div>
                                <li class="ring-in">
                                    <div style="width: 100px;height: 100px;"></div>
                                </li>
                                <li><span class="name">Summary:</span></li>
                                <li>
                                <span class="cost">
                                    $ {{ cartList.summary }}
                                </span>
                                </li>
                                <li>
                                    <a href="{% url 'app:sellteaccounts' %}" class="add-cart item_add" id="addToCart">
                                        settle accounts
                                    </a>
                                </li>
                                <div class="clearfix"></div>
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end-ckeckout-->
{% endblock %}

Reception/templates/contact.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Contact
{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Contact</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--contact-start-->
    <div class="contact">
        <div class="container">
            <div class="contact-top heading">
                <h2>CONTACT</h2>
            </div>
            <div class="contact-text">
                <div class="col-md-3 contact-left">
                    <div class="address">
                        <h5>Address</h5>
                        <p>The company name,
                            <span>Lorem ipsum dolor,</span>
                            Glasglow Dr 40 Fe 72.</p>
                    </div>
                    <div class="address">
                        <h5>Address1</h5>
                        <p>Tel:1115550001,
                            <span>Fax:190-4509-494</span>
                            Email: <a href="mailto:example@email.com">contact@example.com</a></p>
                    </div>
                </div>
                <div class="col-md-9 contact-right">
                    <form method="post" action="{% url 'app:contact' %}">
                        {% if user.is_authenticated %}
                            <input type="text" placeholder="Name" name="name"
                                   value="{{ user.first_name }}.{{ user.last_name }}">
                        {% else %}
                            <input type="text" placeholder="Name" name="name">
                        {% endif %}
                        <input type="text" placeholder="Phone" name="phone" value="{{ user.mobile }}">
                        <input type="text" placeholder="Email" name="email" value="{{ user.email }}">
                        <textarea placeholder="Message" required="" name="message"></textarea>
                        <div class="submit-btn">
                            <input type="submit" value="SUBMIT">
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--contact-end-->
    <!--map-start-->
    {#    <div class="map">#}
    {#        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6632.248000703498!2d151.265683!3d-33.7832959!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12abc7edcbeb07%3A0x5017d681632bfc0!2sManly+Vale+NSW+2093%2C+Australia!5e0!3m2!1sen!2sin!4v1433329298259"#}
    {#                style="border:0"></iframe>#}
    {#    </div>#}
    <!--map-end-->

{% endblock %}

Reception/templates/info.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Information{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Information</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--register-starts-->
    <div class="register">
        <div class="container">
            <div class="register-top heading">
                <h2>INFORMATION</h2>
            </div>
            <form method="post" action="{% url 'app:info' %}">
                <div class="register-main">
                    <div class="col-md-6 account-left">
                        <h2>{{ user.email }}</h2>
                        <h4>Date Joined:{{ user.date_joined }}</h4>
                        <h4>Last Login:{{ user.last_login }}</h4>
                        <input type="hidden" name="uid" value="{{ user.uid }}">
                    </div>
                    <div class="col-md-6 account-left">
                        <input placeholder="First name" type="text" name="first_name" tabindex="1" required
                               value="{{ user.first_name }}">
                        <input placeholder="Last name" type="text" name="last_name" tabindex="2" required
                               value="{{ user.last_name }}">
                        <input placeholder="Mobile" type="text" name="mobile" tabindex="3" required
                               value="{{ user.mobile }}">
                        {% if  user.address %}
                            <input placeholder="Address" type="text" name="address" tabindex="4"
                                   value="{{ user.address }}">
                        {% else %}
                            <input placeholder="Address" type="text" name="address" tabindex="4">
                        {% endif %}
                        <ul>
                            <li>
                                <label class="radio left">
                                    <input type="radio" name="gender"
                                           {% if user.gender == 1 %}checked="checked"{% endif %} value="1">
                                    <i>Male</i>
                                </label>
                            </li>
                            <li>
                                <label class="radio">
                                    <input type="radio" name="gender"
                                           {% if user.gender == 0 %}checked="checked"{% endif %} value="0">
                                    <i>Female</i>
                                </label>
                            </li>
                            <div class="clearfix"></div>
                        </ul>
                        <div class="address submit">
                            <input type="submit" value="Submit">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                {% csrf_token %}
            </form>

        </div>
    </div>
    <!--register-end-->

{% endblock %}

Reception/templates/orders.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Checkout{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Order forms</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--start-ckeckout-->
    <div class="ckeckout">
        <div class="container">
            <div class="ckeck-top heading">
                <h2>ORDER FORMS</h2>
            </div>
            <div class="ckeckout-top">
                <div class="cart-items">

                    <script>$(document).ready(function (c) {
                        $('.close1').on('click', function (c) {
                            $('.cart-header').fadeOut('slow', function (c) {
                                $('.cart-header').remove();
                            });
                        });
                    });
                    </script>
                    <script>$(document).ready(function (c) {
                        $('.close2').on('click', function (c) {
                            $('.cart-header1').fadeOut('slow', function (c) {
                                $('.cart-header1').remove();
                            });
                        });
                    });
                    </script>
                    <script>$(document).ready(function (c) {
                        $('.close3').on('click', function (c) {
                            $('.cart-header2').fadeOut('slow', function (c) {
                                $('.cart-header2').remove();
                            });
                        });
                    });
                    </script>
                    {% for o in olist %}
                        <div class="in-check">
                            <ul class="unit">
                                <li><span>Number:{{ o.0.number }}</span></li>
                                <li>
                                    <span>Status:
                                        {% if o.0.receive_time %}
                                            Finished
                                        {% elif o.0.send_time %}
                                            Transporting
                                        {% elif o.0.pay_time %}
                                            To be delivered
                                        {% else %}
                                            Unpaid
                                        {% endif %}
                                    </span>
                                </li>
                                <li><span>To:{{ o.0.receiver }}</span></li>
                                <li><span>Create time:{{ o.0.create_time }}</span></li>
                                <li></li>
                                <div class="clearfix"></div>
                            </ul>
                            {% for commodity in o.1 %}
                                <ul class="cart-header"
                                    style="margin-bottom: 0;{% if not forloop.last %}border-bottom: none;{% endif %}">
                                    <a href="{% url 'app:removeitem' cid=commodity.0.id %}">
                                        <div class=""></div>
                                    </a>
                                    <li class="ring-in">
                                        <a href="{% url 'app:single' cid=commodity.0.id %}">
                                            <img src="/static/upload/{{ commodity.0.picture_1 }}"
                                                 class="img-responsive"
                                                 alt="{{ commodity.0.cname }}" style="width: 100px;">
                                        </a>
                                    </li>
                                    <li><span class="name">{{ commodity.0.sku }}</span></li>
                                    <li>
                                    <span class="cost">
                                    $ {{ commodity.0.price }} / {{ commodity.1 }}
                                    </span>
                                    </li>
                                    <li><span>Subtotal: $ {{ commodity.2 }}</span></li>
                                    <div class="clearfix"></div>
                                </ul>
                            {% endfor %}
                            <ul class="cart-header">

                                <div></div>
                                <li class="ring-in">
                                    <div style="width: 100px;height: 100px;"></div>
                                </li>
                                <li><span class="name">Summary:</span></li>
                                <li>
                                <span class="cost">
                                    $ {{ o.0.money }}
                                </span>
                                </li>
                                <li>
                                    {% if o.0.receive_time %}
                                        <a href="{% url 'app:deleteorder' %}?id={{ o.0.id }}" class="add-cart item_add"
                                           id="addToCart"
                                           style="width: 170px;text-align: center;">
                                            Delete
                                        </a>
                                    {% elif o.0.send_time %}
                                        <a href="{% url 'app:confirm' %}?id={{ o.0.id }}" class="add-cart item_add"
                                           id="addToCart"
                                           style="width: 170px;text-align: center;">
                                            Confirm receipt
                                        </a>
                                    {% elif o.0.pay_time %}
                                        <a href="" class="add-cart item_add"
                                           id="addToCart"
                                           style="width: 170px;text-align: center;">
                                            Urge
                                        </a>
                                    {% else %}
                                        <a href="{% url 'app:repay' %}?oid={{ order.id }}" class="add-cart item_add"
                                           id="addToCart"
                                           style="width: 170px;text-align: center;">
                                            pay
                                        </a>
                                    {% endif %}

                                </li>
                                <div class="clearfix"></div>
                            </ul>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
    <!--end-ckeckout-->
{% endblock %}

Reception/templates/reset.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Reset{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Reset</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--account-starts-->
    <div class="account">
        <div class="container">
            <div class="account-top heading">
                <h2>RESET</h2>
            </div>
            <div class="account-main">
                <div class="col-md-6 account-left">
                    <h3>Fucking Your Password</h3>
                    <div class="account-bottom">
                        <form method="post" action="{% url 'app:reset' %}">
                            {% csrf_token %}
                            <input placeholder="Email" name="email" type="text" tabindex="3" required>
                            <div class="address">
                                <a class="forgot" style="text-underline: none;" disabled>
                                    Pay attention to your mailbox.
                                </a>
                                <input type="submit" value="Send email">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-6 account-right account-left">
                    <h3>New User? Create an Account</h3>
                    <p>By creating an account with our store, you will be able to move through the checkout process
                        faster,
                        store multiple shipping addresses, view and track your orders in your account and more.</p>
                    <a href="{% url 'app:register' %}">Create an Account</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--account-end-->
{% endblock %}

Reception/templates/resetmail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset password</title>
</head>
<body>
<h3>Dear:{{ user_reset.first_name }}.{{ user_reset.last_name }}</h3>

<h3>Please click <a href="http://49.234.99.134/reset_password/?uid={{ user_reset.uid }}">RESET PASSWORD</a> to reset your password</h3>

</body>
</html>

Reception/templates/settle.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Accounts{% endblock %}
{% block content %}
    <!--start-breadcrumbs-->
    <div class="breadcrumbs">
        <div class="container">
            <div class="breadcrumbs-main">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Accounts</li>
                </ol>
            </div>
        </div>
    </div>
    <!--end-breadcrumbs-->
    <!--start-ckeckout-->
    <div class="ckeckout">
        <div class="container">
            <div class="ckeck-top heading">
                <h2>ACCOUNTS</h2>
            </div>
            <div class="ckeckout-top">
                <form method="post" action="{% url 'app:pay' %}">
                    {% csrf_token %}
                    <div class="cart-items">
                        <h3>New Accounts ({{ styles.4.count }})</h3>
                        <script>$(document).ready(function (c) {
                            $('.close1').on('click', function (c) {
                                $('.cart-header').fadeOut('slow', function (c) {
                                    $('.cart-header').remove();
                                });
                            });
                        });
                        </script>
                        <script>$(document).ready(function (c) {
                            $('.close2').on('click', function (c) {
                                $('.cart-header1').fadeOut('slow', function (c) {
                                    $('.cart-header1').remove();
                                });
                            });
                        });
                        </script>
                        <script>$(document).ready(function (c) {
                            $('.close3').on('click', function (c) {
                                $('.cart-header2').fadeOut('slow', function (c) {
                                    $('.cart-header2').remove();
                                });
                            });
                        });
                        </script>

                        <div class="in-check">
                            <ul class="unit">
                                <li><span>Item</span></li>
                                <li><span>Product Name</span></li>
                                <li><span>Unit Price / Amount</span></li>
                                <li><span>Subtotal / Delivery Details</span></li>
                                <li></li>
                                <div class="clearfix"></div>
                            </ul>
                            {% for commodity in styles.4 %}
                                <input type="hidden" name="cid" value="{{ commodity.product.id }}">
                                <ul class="cart-header">
                                    <a href="{% url 'app:removeitem' cid=commodity.product.id %}">
                                        <div></div>
                                    </a>
                                    <li class="ring-in">
                                        <a href="{% url 'app:single' cid=commodity.product.id %}">
                                            <img src="/static/upload/{{ commodity.product.picture_1 }}"
                                                 class="img-responsive"
                                                 alt="{{ commodity.product.cname }}" style="width: 100px;">
                                        </a>
                                    </li>
                                    <li><span class="name">{{ commodity.product.sku }}</span></li>
                                    <li>
                                    <span class="cost">
                                    $ {{ commodity.product.price }} / {{ commodity.quantity }}
                                    </span>
                                        <input type="hidden" name="quantity{{ commodity.product.id }}"
                                               value="{{ commodity.quantity }}">
                                    </li>
                                    <li><span>$ {{ commodity.total_price }} / Free</span>
                                        <p></p></li>
                                    <div class="clearfix"></div>
                                </ul>
                            {% endfor %}
                        </div>
                    </div>
                    {% if styles.4.count > 0 %}
                        <div class="register-main">
                            <div class="col-md-6 account-left">
                                <input placeholder="Who will receive the goods" type="text" name="receiver"
                                       tabindex="1" value="{{ user.first_name }}.{{ user.last_name }}" required>
                                <input placeholder="Address" type="text" name="address" tabindex="2" required>
                                <input placeholder="Mobile" type="text" name="mobile" tabindeix="3" required>
                                <span class="name">Summary:</span> &nbsp;&nbsp
                                <span class="cost">${{ styles.4.summary }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input type="text" name="summary" value="{{ styles.4.summary }}" style="display: none">
                                <div class="submit-btn" style="float: right">
                                    <input type="submit" value="GO TO PAY">
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <!--end-ckeckout-->
{% endblock %}